name: Convert PNG images to WebP

on:
  push:
  workflow_dispatch:

jobs:

  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: ./.github/scripts/convert-webp.command
        shell: bash