name: Convert PNG images to WebP

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  convert:
    runs-on: macos-12
    steps:
      - name: Run script
        run: "./.github/scripts/convert-webp.command"
        shell: bash
      - name: Commit
        run: |
          git config user.name "Yaacoub"
          git config user.email "yaapete.dev@gmail.com"
          git add -A
          git commit -m "⚙️ Auto-generate WebP images"
      - name: Push
        run: |
          git push