name: Convert PNG images to WebP

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  convert:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run script
        run: "./.github/scripts/convert-webp.command"
        shell: bash
      - name: Commit
        run: |
          git config --global user.name "Yaacoub"
          git config --global user.email "yaapete.dev@gmail.com"
          git add -f .
          git diff-index --quiet HEAD || git commit -m "Auto-generate WebP images"
      - name: Push
        run: |
          git push